# Generated by Django 5.1 on 2024-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.CharField(max_length=100)),
                ('equip_num', models.PositiveSmallIntegerField()),
                ('subname', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('installed_date', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('register_date', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
