# Generated by Django 5.1 on 2024-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default='Default Value', editable=False, primary_key=True, serialize=False)),
                ('equip', models.CharField(max_length=100)),
                ('equip_num', models.PositiveSmallIntegerField()),
                ('subname', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=50)),
                ('asset_id', models.CharField(max_length=20)),
                ('installed_date', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('register_date', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
